# Generated by Django 4.2.9 on 2024-09-18 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seo_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprovider',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='seo_manager.clientgroup'),
        ),
        migrations.CreateModel(
            name='GoogleAnalyticsCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_id', models.CharField(max_length=100)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_uri', models.URLField()),
                ('ga_client_id', models.CharField(max_length=100)),
                ('client_secret', models.CharField(max_length=100)),
                ('scopes', models.JSONField(default=list)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ga_credentials', to='seo_manager.client')),
            ],
        ),
    ]
