# Generated by Django 4.2.9 on 2024-09-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_manager', '0002_alter_aiprovider_model_alter_aiprovider_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleanalyticscredentials',
            name='scopes',
        ),
        migrations.AddField(
            model_name='googleanalyticscredentials',
            name='service_account_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googleanalyticscredentials',
            name='use_service_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='googleanalyticscredentials',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googleanalyticscredentials',
            name='client_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googleanalyticscredentials',
            name='ga_client_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googleanalyticscredentials',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googleanalyticscredentials',
            name='token_uri',
            field=models.URLField(blank=True, null=True),
        ),
    ]
