# Generated by Django 4.2.9 on 2024-09-18 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo_manager', '0003_remove_googleanalyticscredentials_scopes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='googleanalyticscredentials',
            old_name='view_id',
            new_name='property_id',
        ),
    ]
