# Generated by Django 4.2.9 on 2024-09-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_manager', '0004_rename_view_id_googleanalyticscredentials_property_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='googleanalyticscredentials',
            old_name='property_id',
            new_name='view_id',
        ),
        migrations.AlterField(
            model_name='googleanalyticscredentials',
            name='access_token',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='googleanalyticscredentials',
            name='client_secret',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='googleanalyticscredentials',
            name='ga_client_id',
            field=models.CharField(default='placeholder_client_id', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='googleanalyticscredentials',
            name='refresh_token',
            field=models.TextField(default='refresh_token'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='googleanalyticscredentials',
            name='token_uri',
            field=models.URLField(default='token_uri'),
            preserve_default=False,
        ),
    ]
