# Generated by Django 4.2.9 on 2024-09-18 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seo_manager', '0006_alter_googleanalyticscredentials_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchConsoleCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_url', models.URLField()),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_uri', models.URLField(blank=True, null=True)),
                ('sc_client_id', models.CharField(blank=True, max_length=100, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sc_credentials', to='seo_manager.client')),
            ],
        ),
    ]
