# Generated by Django 4.2.9 on 2024-09-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_manager', '0007_searchconsolecredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleanalyticscredentials',
            name='scopes',
            field=models.JSONField(default=list),
        ),
    ]
