# Generated by Django 4.2.9 on 2024-09-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_manager', '0008_googleanalyticscredentials_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleanalyticscredentials',
            name='user_email',
            field=models.EmailField(default='test@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
