# Generated by Django 4.2.9 on 2024-10-03 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seo_manager', '0009_googleanalyticscredentials_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummarizerUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('compressed_content', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField()),
                ('content_token_size', models.IntegerField()),
                ('content_character_count', models.IntegerField()),
                ('total_input_tokens', models.IntegerField()),
                ('total_output_tokens', models.IntegerField()),
                ('model_used', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
