# Generated by Django 4.2.9 on 2024-10-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_manager', '0010_summarizerusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='business_objectives',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
