# Generated by Django 4.2.9 on 2024-10-27 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seo_manager', '0013_client_target_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_profile',
            field=models.TextField(blank=True, help_text="Detailed 300-500 word profile of the client's business, goals, and SEO strategy"),
        ),
        migrations.CreateModel(
            name='TargetedKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('priority', models.IntegerField(choices=[(1, 'Highest'), (2, 'High'), (3, 'Medium'), (4, 'Low'), (5, 'Lowest')], default=3, help_text='Priority level for this keyword')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeted_keywords', to='seo_manager.client')),
            ],
            options={
                'ordering': ['priority', 'keyword'],
                'unique_together': {('client', 'keyword')},
            },
        ),
        migrations.CreateModel(
            name='SEOProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('implementation_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('documentation_file', models.FileField(blank=True, null=True, upload_to='seo_projects/%Y/%m/')),
                ('initial_rankings', models.JSONField(default=dict, help_text='Snapshot of keyword rankings before project implementation')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_projects', to='seo_manager.client')),
                ('targeted_keywords', models.ManyToManyField(related_name='related_projects', to='seo_manager.targetedkeyword')),
            ],
            options={
                'ordering': ['-implementation_date'],
            },
        ),
        migrations.CreateModel(
            name='KeywordRankingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('ctr', models.FloatField(help_text='Click-through rate as a decimal (e.g., 0.15 for 15%)', verbose_name='Click-Through Rate')),
                ('average_position', models.FloatField()),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_history', to='seo_manager.targetedkeyword')),
            ],
            options={
                'ordering': ['-date'],
                'get_latest_by': 'date',
                'unique_together': {('keyword', 'date')},
            },
        ),
    ]
