# Generated by Django 4.2.9 on 2024-10-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_manager', '0015_alter_keywordrankinghistory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='keywordrankinghistory',
            index=models.Index(fields=['-date'], name='seo_manager_date_1dddca_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordrankinghistory',
            index=models.Index(fields=['client', '-date'], name='seo_manager_client__5df230_idx'),
        ),
    ]
