# Generated by Django 5.1.2 on 2024-11-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_manager', '0016_keywordrankinghistory_seo_manager_date_1dddca_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='distilled_website',
            field=models.TextField(blank=True, help_text="Distilled version of the client's website content for SEO purposes"),
        ),
        migrations.AddField(
            model_name='client',
            name='distilled_website_date',
            field=models.DateTimeField(blank=True, help_text='The last time the distilled website content was modified or created', null=True),
        ),
    ]
