# Generated by Django 4.2.9 on 2024-11-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_manager', '0017_client_distilled_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchconsolecredentials',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
