# Generated by Django 4.2.9 on 2024-11-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_manager', '0019_remove_searchconsolecredentials_token_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleanalyticscredentials',
            name='ga_property_id',
            field=models.CharField(help_text='GA4 property ID (format: 123456789)', max_length=255, null=True),
        ),
    ]
