# Generated by Django 4.2.9 on 2024-11-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_manager', '0022_searchconsolecredentials_last_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchconsolecredentials',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
