# Generated by Django 4.2.9 on 2024-10-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_task_callback_task_config_task_converter_cls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='allow_code_execution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='cache',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='function_calling_llm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='max_execution_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='max_iter',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='agent',
            name='max_retry_limit',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='agent',
            name='max_rpm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='prompt_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='respect_context_window',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='response_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='step_callback',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='system_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='use_system_prompt',
            field=models.BooleanField(default=True),
        ),
    ]
