# Generated by Django 4.2.9 on 2024-10-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_allow_code_execution_agent_cache_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='schema',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='tool_class',
            field=models.CharField(choices=[('docx_search_tool', 'docx_search_tool'), ('csv_search_tool', 'csv_search_tool'), ('crawl_website_tool', 'crawl_website_tool'), ('rag', 'rag'), ('google_suggestions_tool', 'google_suggestions_tool'), ('screenshot_tool', 'screenshot_tool'), ('file_writer_tool', 'file_writer_tool'), ('searxng_tool', 'searxng_tool'), ('directory_read_tool', 'directory_read_tool'), ('browser_tools', 'browser_tools'), ('keyword_tools', 'keyword_tools'), ('google_analytics_tool', 'google_analytics_tool'), ('file_read_tool', 'file_read_tool'), ('directory_search_tool', 'directory_search_tool')], default='None', max_length=100),
            preserve_default=False,
        ),
    ]
