# Generated by Django 4.2.9 on 2024-10-08 04:29

import apps.agents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_crew_config_crew_embedder_crew_function_calling_llm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='embedder',
            field=models.JSONField(default=apps.agents.models.default_embedder),
        ),
    ]
