# Generated by Django 4.2.9 on 2024-10-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_alter_crew_embedder'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewexecution',
            name='human_input_request',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crewexecution',
            name='human_input_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crewexecution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('WAITING_FOR_HUMAN_INPUT', 'Waiting for Human Input'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=25),
        ),
    ]
