# Generated by Django 4.2.9 on 2024-10-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_crewexecution_human_input_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewexecution',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='llm',
            field=models.CharField(default='gpt-3.5-turbo', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
