# Generated by Django 4.2.9 on 2024-10-09 21:00

import apps.agents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_pipeline_pipelineexecution_pipelinestage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='avatar',
            field=models.CharField(default=apps.agents.models.random_avatar, max_length=100),
        ),
    ]
