# Generated by Django 4.2.9 on 2024-10-10 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_agent_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewmessage',
            name='agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crewmessage',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agents.crewexecution'),
        ),
    ]
