# Generated by Django 4.2.9 on 2024-10-10 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_rename_output_crewoutput_raw_remove_crewoutput_crew_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='step_callback',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='task_callback',
        ),
    ]
