# Generated by Django 4.2.9 on 2024-10-11 23:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0016_crewtask_crew_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='input_variables',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, help_text='List of input variables required for crew execution', null=True, size=None),
        ),
    ]
