# Generated by Django 4.2.9 on 2024-10-12 17:02

import apps.agents.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0017_crew_input_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='crew_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.crewexecution'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='input_variables',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.agents.models.user_directory_path),
        ),
    ]
