# Generated by Django 4.2.9 on 2024-10-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0019_remove_tool_schema_tool_tool_subclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='module_path',
            field=models.CharField(default='.', max_length=255),
            preserve_default=False,
        ),
    ]
