# Generated by Django 4.2.9 on 2024-10-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0021_alter_task_output_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='function_calling_llm',
            field=models.CharField(blank=True, default='llama3:8b-instruct-fp16', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='llm',
            field=models.CharField(default='llama3:8b-instruct-fp16', max_length=100),
        ),
        migrations.AlterField(
            model_name='crew',
            name='function_calling_llm',
            field=models.CharField(blank=True, default='llama3:8b-instruct-fp16', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='manager_llm',
            field=models.CharField(blank=True, default='llama3:8b-instruct-fp16', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='planning_llm',
            field=models.CharField(blank=True, default='llama3:8b-instruct-fp16', max_length=100, null=True),
        ),
    ]
