# Generated by Django 4.2.9 on 2024-10-29 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0023_alter_agent_function_calling_llm_alter_agent_llm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentToolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_output_as_result', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_settings', to='agents.agent')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.tool')),
            ],
            options={
                'unique_together': {('agent', 'tool')},
            },
        ),
    ]
