# Generated by Django 5.1.2 on 2024-11-22 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0027_executionstage'),
        ('seo_manager', '0021_remove_googleanalyticscredentials_ga_property_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crewexecution',
            name='outputs',
        ),
        migrations.RemoveField(
            model_name='crewoutput',
            name='execution',
        ),
        migrations.AddField(
            model_name='crewexecution',
            name='crew_output',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew_execution', to='agents.crewoutput'),
        ),
        migrations.AddField(
            model_name='crewexecution',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crewexecution',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seo_manager.client'),
        ),
        migrations.AlterField(
            model_name='crewexecution',
            name='inputs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crewexecution',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
