# Generated by Django 5.1.2 on 2024-11-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0028_remove_crewexecution_outputs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewmessage',
            name='crewai_task_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executionstage',
            name='crewai_task_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
