# Generated by Django 4.2.9 on 2024-11-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0030_conversation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executionstage',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='executionstage',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='executionstage',
            name='stage_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='executionstage',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='executionstage',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
