# Generated by Django 4.2.9 on 2024-11-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0031_alter_executionstage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executionstage',
            options={'ordering': ['created_at'], 'verbose_name': 'Execution Stage', 'verbose_name_plural': 'Execution Stages'},
        ),
        migrations.AddField(
            model_name='crewexecution',
            name='task_mapping',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='executionstage',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='executionstage',
            name='stage_type',
            field=models.CharField(choices=[('task_start', 'Task Start'), ('thinking', 'Thinking'), ('tool_usage', 'Tool Usage'), ('tool_results', 'Tool Results'), ('human_input', 'Human Input'), ('completion', 'Completion')], max_length=20),
        ),
        migrations.AlterField(
            model_name='executionstage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='executionstage',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
