# Generated by Django 4.2.9 on 2024-11-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0032_alter_executionstage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewexecution',
            name='current_task_id',
            field=models.IntegerField(null=True),
        ),
    ]
