# Generated by Django 4.2.9 on 2024-11-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0033_crewexecution_current_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewexecution',
            name='current_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
