# Generated by Django 4.2.9 on 2024-11-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0034_alter_crewexecution_current_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crewexecution',
            name='current_task_id',
        ),
        migrations.AddField(
            model_name='crewexecution',
            name='current_task',
            field=models.JSONField(blank=True, help_text='Stores current task execution info', null=True),
        ),
        migrations.AlterField(
            model_name='crewexecution',
            name='task_mapping',
            field=models.JSONField(blank=True, help_text='Maps CrewAI task IDs to our task IDs', null=True),
        ),
    ]
