# Generated by Django 5.1.2 on 2024-12-02 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0035_remove_crewexecution_current_task_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crewexecution',
            name='current_task',
        ),
        migrations.RemoveField(
            model_name='crewexecution',
            name='task_mapping',
        ),
        migrations.CreateModel(
            name='ToolRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('inputs', models.JSONField()),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.tool')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
